// src/mockData.js

export const insightsData = [
  {
    title: "All Patients",
    total: 170,
    color: "bg-pink-100",
    hasGraph: false,
    hasPiechart: true,
    diseases: [
      { name: "COPD", value: 20, color: "#FF6384" },
      { name: "Asthma", value: 50, color: "#36A2EB" },
      { name: "TB", value: 30, color: "#FFCE56" },
    ],
  },
  {
    title: "New Registrations",
    total: 62,
    color: "bg-green-100",
    hasGraph: true,
    hasPiechart: false,
    details: { "last 7 days": "+10%" },
  },
  {
    title: "Previous Appointments",
    total: 13,
    color: "bg-red-100",
    hasGraph: true,
    hasPiechart: false,
    details: { "last 7 days": "-0.6%" },
  },
  {
    title: "Appointments Today",
    total: 12,
    color: "bg-purple-100",
    hasGraph: false,
    hasPiechart: true,
    diseases: [
      { name: "COPD", value: 3, color: "#FF6384" },
      { name: "Asthma", value: 8, color: "#36A2EB" },
      { name: "TB", value: 3, color: "#FFCE56" },
    ],
  },
  {
    title: "Follow-ups",
    total: 29,
    color: "bg-blue-100",
    hasGraph: true,
    hasPiechart: false,
    details: { "last 30 days": "+15%" },
  },
  {
    title: "Surgeries Scheduled",
    total: 5,
    color: "bg-yellow-100",
    hasGraph: true,
    hasPiechart: false,
    details: { "last month": "+20%" },
  },
  {
    title: "Discharged Patients",
    total: 45,
    color: "bg-orange-100",
    hasGraph: true,
    hasPiechart: false,
    details: { "last 30 days": "-5%" },
  },
  {
    title: "Critical Patients",
    total: 7,
    color: "bg-teal-100",
    hasGraph: false,
    hasPiechart: true,
    diseases: [
      { name: "COPD", value: 2, color: "#FF6384" },
      { name: "Asthma", value: 4, color: "#36A2EB" },
      { name: "TB", value: 1, color: "#FFCE56" },
    ],
  },
  {
    title: "Laboratory Tests",
    total: 120,
    color: "bg-gray-100",
    hasGraph: true,
    hasPiechart: false,
    details: { "last 7 days": "+8%" },
  },
  {
    title: "Emergency Visits",
    total: 15,
    color: "bg-indigo-100",
    hasGraph: false,
    hasPiechart: true,
    diseases: [
      { name: "COPD", value: 4, color: "#FF6384" },
      { name: "Asthma", value: 6, color: "#36A2EB" },
      { name: "TB", value: 5, color: "#FFCE56" },
    ],
  },
];
